name: Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate_homeworks:
    name: Validate new homework
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check flake8
        run: flake8 ./05/

      - name: Check pylint
        if: ${{ always() }}
        run: pylint ./05/*.py

      - name: Run tests with unittest
        run: coverage run -m unittest discover -s 05 -p 'test_*.py'

      - name: Check test coverage
        run: coverage report -m
