name: Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate_homeworks:
    name: Validate new homework
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check flake8
        run: flake8 $(find . -type d -not -path '*/.*' -print)

      - name: Check pylint
        if: ${{ always() }}
        run: pylint $(find . -name '*.py' -not -path '*/.*')

      - name: Run tests with unittest
        run: coverage run -m unittest -s . -p "test_*.py"

      - name: Check test coverage
        run: coverage report -m
