name: Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate_homeworks:
    name: Validate new homework
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check all directories
        run: |
          find . -mindepth 1 -maxdepth 1 -type d ! -name '.*' -exec sh -c '
            flake8 "$1" && \
            pylint "$1/*.py" && \
            coverage run -m unittest discover -s "$1" -p "test_*.py"
          ' \;

      - name: Check test coverage
        run: coverage report -m
